/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.bibliotecamagica.InterfazGrafica;

import com.mycompany.bibliotecamagica.Backend.Entidades.Biblioteca;
import com.mycompany.bibliotecamagica.Backend.Entidades.Libro;
import com.mycompany.bibliotecamagica.Backend.Estructuras.Arboles.ArbolAVL.NodoAVL;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielh
 */
public class EliminacionLibro extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminacionLibro.class.getName());
    private Biblioteca biblio;
    /**
     * Creates new form EliminacionLibro
     */
    public EliminacionLibro(java.awt.Frame parent, boolean modal, Biblioteca biblio) {
        super(parent, modal);
        this.biblio = biblio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jLabel1.setText("ELIMINACION DEL LIBRO:");

        jLabel2.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jLabel2.setText("Ingrese el titulo del libro a eliminar: ");

        jTextField1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String titulo = jTextField1.getText().trim();

        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "⚠️ Ingrese el título del libro que desea eliminar.",
                "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        NodoAVL nodo = biblio.getArbolTitulo().buscar(titulo);
        if (nodo == null || nodo.getLibro() == null) {
            JOptionPane.showMessageDialog(this,
                "❌ No se encontró ningún libro con el título: " + titulo,
                "No encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Libro libro = nodo.getLibro();

        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el libro \"" + libro.getTitulo() + "\"?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // 🧾 Verificar si hay más copias
        if (libro.getNumCopias() > 1) {
            libro.setNumCopias(libro.getNumCopias() - 1);
            JOptionPane.showMessageDialog(this,
                "📘 Se eliminó una copia de \"" + libro.getTitulo() + "\".\n" +
                "Copias restantes: " + libro.getNumCopias(),
                "Copia eliminada", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        biblio.getCatalogo().eliminarLibro(libro.getTitulo());
        biblio.getArbolTitulo().eliminar(libro.getTitulo());
        biblio.getArbolAnio().eliminar(libro.getAnio(), libro);
        biblio.getArbolGenero().eliminarPorTitulo(libro.getTitulo());
        biblio.getTabla().eliminar(libro.getIsnbNum());

        JOptionPane.showMessageDialog(this,
            "✅ Libro \"" + libro.getTitulo() + "\" eliminado completamente del sistema.",
            "Libro eliminado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
