/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.bibliotecamagica.InterfazGrafica;

import com.mycompany.bibliotecamagica.Backend.Control;
import com.mycompany.bibliotecamagica.Backend.Entidades.Biblioteca;
import com.mycompany.bibliotecamagica.Backend.Entidades.Libro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabrielh
 */
public class ListarLibros extends javax.swing.JInternalFrame {
    private long tiempoIntercambio = -1;
    private long tiempoSeleccion = -1;
    private long tiempoInsercion = -1;
    private long tiempoShell = -1;
    private long tiempoQuick = -1;
    /**
     * Creates new form ListarLibros
     */
    public ListarLibros(Control control, Biblioteca biblio) {
        initComponents();
        llenarComboBox();
        jcbTipoDeLista.addActionListener(e -> {
            String tipo = (String) jcbTipoDeLista.getSelectedItem();
            if (tipo != null) {
                List<Libro> libros = new ArrayList<>();
                switch (tipo) {
                    case "Por Titulo, metodo intercambio": {
                        long inicio = System.nanoTime();
                        libros = control.listarIntercambio(biblio.getArbolTitulo());
                        long fin = System.nanoTime();
                        tiempoIntercambio = fin - inicio;

                        break;
                    }

                    case "Por ISBN, metodo selec. directa": {
                        long inicio = System.nanoTime();
                        libros = control.listarPorSelec(biblio.getTabla());
                        long fin = System.nanoTime();
                        tiempoSeleccion = fin - inicio;
                        break;
                    }

                    case "Por autor, metodo inser. directa": {
                        long inicio = System.nanoTime();
                        libros = control.listarPorInser(biblio.getCatalogo());
                        long fin = System.nanoTime();
                        tiempoInsercion = fin - inicio;
                        break;
                    }

                    case "Por año, metodo Shell": {
                        long inicio = System.nanoTime();
                        libros = control.listarPorAnio(biblio.getCatalogo());
                        long fin = System.nanoTime();
                        tiempoShell = fin - inicio;
                        break;
                    }

                    case "Por titulo, metodo QuickSort": {
                        long inicio = System.nanoTime();
                        libros = control.listarPorQuick(biblio.getCatalogo());
                        long fin = System.nanoTime();
                        tiempoQuick = fin - inicio;
                        break;
                    }
                }

                llenarTabla(libros);
            }
        });
    }
    
    
    private void llenarTabla(List<Libro> libros) {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][] {},
            new String[] {"Titulo", "ISBN", "Genero", "Autor", "Año"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        jTable1.setModel(modelo);

        jTable1.getTableHeader().setReorderingAllowed(false);

        for (Libro libro : libros) {
            modelo.addRow(new Object[]{
                libro.getTitulo(),
                libro.getIsnb(),
                String.join("/", libro.getGeneros()),
                libro.getAutor(),
                libro.getAnio()
            });
        }

    }

    
    private void llenarComboBox(){
        jcbTipoDeLista.removeAllItems();
        jcbTipoDeLista.addItem("Por Titulo, metodo intercambio");
        jcbTipoDeLista.addItem("Por ISBN, metodo selec. directa");
        jcbTipoDeLista.addItem("Por autor, metodo inser. directa");
        jcbTipoDeLista.addItem("Por año, metodo Shell");
        jcbTipoDeLista.addItem("Por titulo, metodo QuickSort");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbTipoDeLista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Isbn", "Genero", "Autor", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jcbTipoDeLista.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jcbTipoDeLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jLabel1.setText("LISTAR LIBROS: ");

        jButton1.setFont(new java.awt.Font("URW Bookman", 0, 12)); // NOI18N
        jButton1.setText("Comparar tiempo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119)
                        .addComponent(jcbTipoDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTipoDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
                "Tiempo metodo intercambio : "+tiempoIntercambio+"\n"+
                "Tiempo metodo seleccion : "+tiempoSeleccion+"\n"+
                "Tiempo metodo insercion : "+tiempoInsercion+"\n"+
                "Tiempo metodo Shell : "+tiempoShell+"\n"+
                "Tiempo metodo QuickSort : "+tiempoQuick+"\n", 
                "COMPARACION DE TIEMPOS: ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbTipoDeLista;
    // End of variables declaration//GEN-END:variables
}
